name: Test and Coverage Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.1

      - name: Install gocov
        run: go install github.com/axw/gocov/gocov@latest

      - name: Run tests and coverage
        run: |
          go test -race -coverprofile=coverage.out ./...
          gocov convert coverage.out > coverage.json

      - name: Upload coverage to CodeClimate
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
        with:
          coverageLocations: coverage.json:gocov
          debug: false

      - name: Cleanup
        run: |
          rm -f coverage.out
          rm -f coverage.json