name: Test and Coverage Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests and coverage
        run: |
          go test -race -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out -o coverage.txt

      - name: Upload coverage to CodeClimate
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
        with:
          name: Test Coverage Report
          coverageCommand: go tool cover -json=coverage.out | codeclimate analyze-coverage --input=- --language=go
          verbose: true
          debug: false

      - name: Cleanup
        run: |
          rm -f coverage.out
          rm -f coverage.txt